### ISSUE TITLE
Uncaught Exception "Deno.permissions.querySync is not a function" when using Deno Deploy CLI

### ISSUE THREAD

**Issue by chillbrodev** [getsentry/sentry-deno#1]
### Environment

7.94.1 

### Steps to Reproduce

1. Import Sentry via: `import * as Sentry from 'https://deno.land/x/sentry@7.94.1/index.mjs';` in any typescript file.
2. Run Deno Deploy: `deployctl deploy --project=<SOME_PROJECT> ./src/main.ts`
3. See exception:

```
 Using config file 'deno.jsonc'
✔ Deploying to project <SOME_PROJECT>.
✔ Entrypoint: /src/main.ts
ℹ Uploading all files from the current dir (server)
✔ Found 62 assets.
✔ Uploaded 5 new assets.
✖ Deployment failed.
error: The deployment failed: UNCAUGHT_EXCEPTION

TypeError: Deno.permissions.querySync is not a function
    at getHostName (https://deno.land/x/sentry@7.94.1/index.mjs:11183:35)
    at new DenoClient (https://deno.land/x/sentry@7.94.1/index.mjs:11215:41)
    at initAndBind (https://deno.land/x/sentry@7.94.1/index.mjs:10396:18)
    at Module.init (https://deno.land/x/sentry@7.94.1/index.mjs:12445:3)
    at file:///src/src/main.ts:25:9
    at eventLoopTick (ext:core/01_core.js:182:7)
``` 

### Expected Result

Expected result is that Deno Deploy works without issue.
Deployment works when using Sentry via the npm import: `import * as Sentry from 'npm:@sentry/node'`

### Actual Result

Deno Deploy fails. Here are the logs from Deno Deploy portal:

```
Cloning repository (100%)
Downloaded
file:///src/src/main.ts
Downloaded
https://deno.land/std@0.202.0/dotenv/mod.ts
Downloaded
https://deno.land/x/hono@v3.12.0/mod.ts
Downloaded
https://deno.land/x/hono@v3.12.0/middleware.ts
Downloaded
file:///src/src/clients/redis/redis_client.ts
Downloaded
file:///src/src/features/articles/articles.service.ts
Downloaded
file:///src/src/clients/project_media/project_media_client.ts
Downloaded
file:///src/src/features/articles/articles.controller.ts
Downloaded
file:///src/src/middlewares/error_handler/error_handler.ts
Downloaded
https://deno.land/x/sentry@7.94.1/index.mjs
Downloaded
file:///src/src/features/account/account.controller.ts
Downloaded
file:///src/src/features/account/account.service.ts
Downloaded
file:///src/src/clients/project_account/project_account_client.ts
Downloaded
file:///src/src/middlewares/logger/custom_hono_logger.ts
Downloaded
https://deno.land/std@0.53.0/fmt/colors.ts
Downloaded
https://deno.land/x/hono@v3.12.0/hono.ts
Downloaded
https://deno.land/x/hono@v3.12.0/http-exception.ts
Downloaded
https://deno.land/x/hono@v3.12.0/router/reg-exp-router/index.ts
Downloaded
https://deno.land/x/hono@v3.12.0/router/trie-router/index.ts
Downloaded
https://deno.land/x/hono@v3.12.0/router/smart-router/index.ts
Downloaded
https://deno.land/x/hono@v3.12.0/router/pattern-router/index.ts
Downloaded
https://deno.land/x/hono@v3.12.0/router/linear-router/index.ts
Downloaded
https://deno.land/x/hono@v3.12.0/validator/index.ts
Downloaded
https://deno.land/x/hono@v3.12.0/client/index.ts
Downloaded
https://deno.land/x/hono@v3.12.0/middleware/basic-auth/index.ts
Downloaded
https://deno.land/x/hono@v3.12.0/middleware/bearer-auth/index.ts
Downloaded
https://deno.land/x/hono@v3.12.0/middleware/cache/index.ts
Downloaded
https://deno.land/x/hono@v3.12.0/helper/cookie/index.ts
Downloaded
https://deno.land/x/hono@v3.12.0/middleware/compress/index.ts
Downloaded
https://deno.land/x/hono@v3.12.0/middleware/cors/index.ts
Downloaded
https://deno.land/x/hono@v3.12.0/middleware/csrf/index.ts
Downloaded
https://deno.land/x/hono@v3.12.0/middleware/etag/index.ts
Downloaded
https://deno.land/x/hono@v3.12.0/helper/html/index.ts
Downloaded
https://deno.land/x/hono@v3.12.0/jsx/index.ts
Downloaded
https://deno.land/x/hono@v3.12.0/middleware/jsx-renderer/index.ts
Downloaded
https://deno.land/x/hono@v3.12.0/middleware/jwt/index.ts
Downloaded
https://deno.land/x/hono@v3.12.0/middleware/logger/index.ts
Downloaded
https://deno.land/x/hono@v3.12.0/middleware/powered-by/index.ts
Downloaded
https://deno.land/x/hono@v3.12.0/middleware/timing/index.ts
Downloaded
https://deno.land/x/hono@v3.12.0/middleware/pretty-json/index.ts
Downloaded
https://deno.land/x/hono@v3.12.0/middleware/secure-headers/index.ts
Downloaded
https://deno.land/x/hono@v3.12.0/adapter/deno/serve-static.ts
Downloaded
https://deno.land/x/redis@v0.32.0/mod.ts
Downloaded
file:///src/src/clients/project_media/models/project_media.interfaces.ts
Downloaded
file:///src/src/features/articles/articles.interfaces.ts
Downloaded
file:///src/src/clients/project_media/find_included.ts
Downloaded
file:///src/src/features/articles/parser/content_parser.ts
Downloaded
file:///src/src/features/articles/parser/errors/parse_data_failed.ts
Downloaded
file:///src/src/features/articles/parser/interest_parser.ts
Downloaded
file:///src/src/features/articles/parameters/get_articles_params.ts
Downloaded
file:///src/src/features/articles/filters/is_live_blog_filter.ts
Downloaded
file:///src/src/features/articles/filters/air_date_in_future_filter.ts
Downloaded
file:///src/src/clients/project_media/errors/project_media_not_found.ts
Downloaded
file:///src/src/referer.ts
Downloaded
file:///src/src/errors/ensure_error.ts
Downloaded
file:///src/src/middlewares/logger/sentry_exception_logger.ts
Downloaded
file:///src/src/clients/project_account/errors/project_account_error.ts
Downloaded
file:///src/src/clients/project_account/models/project_account.interface.ts
Downloaded
file:///src/src/features/account/account.interfaces.ts
Downloaded
https://deno.land/x/zod@v3.22.4/mod.ts
Downloaded
https://deno.land/x/hono@v3.12.0/hono-base.ts
Downloaded
https://deno.land/x/hono@v3.12.0/router/reg-exp-router/router.ts
Downloaded
https://deno.land/x/hono@v3.12.0/router/trie-router/router.ts
Downloaded
https://deno.land/x/hono@v3.12.0/router/smart-router/router.ts
Downloaded
https://deno.land/x/hono@v3.12.0/router/pattern-router/router.ts
Downloaded
https://deno.land/x/hono@v3.12.0/router/linear-router/router.ts
Downloaded
https://deno.land/x/hono@v3.12.0/validator/validator.ts
Downloaded
https://deno.land/x/hono@v3.12.0/client/client.ts
Downloaded
https://deno.land/x/hono@v3.12.0/utils/buffer.ts
Downloaded
https://deno.land/x/hono@v3.12.0/utils/encode.ts
Downloaded
https://deno.land/x/hono@v3.12.0/utils/cookie.ts
Downloaded
https://deno.land/x/hono@v3.12.0/utils/crypto.ts
Downloaded
https://deno.land/x/hono@v3.12.0/utils/html.ts
Downloaded
https://deno.land/x/hono@v3.12.0/jsx/components.ts
Downloaded
https://deno.land/x/hono@v3.12.0/jsx/streaming.ts
Downloaded
https://deno.land/x/hono@v3.12.0/utils/jwt/index.ts
Downloaded
https://deno.land/x/hono@v3.12.0/context.ts
Downloaded
https://deno.land/x/hono@v3.12.0/utils/url.ts
Downloaded
https://deno.land/x/hono@v3.12.0/utils/filepath.ts
Downloaded
https://deno.land/x/hono@v3.12.0/utils/mime.ts
Downloaded
https://deno.land/x/redis@v0.32.0/protocol/shared/types.ts
Downloaded
https://deno.land/x/redis@v0.32.0/redis.ts
Downloaded
https://deno.land/x/redis@v0.32.0/errors.ts
Downloaded
file:///src/src/features/articles/parser/article_content.interfaces.ts
Downloaded
file:///src/src/logger.ts
Downloaded
file:///src/src/errors/base_error.ts
Downloaded
https://deno.land/x/zod@v3.22.4/index.ts
Downloaded
https://deno.land/x/hono@v3.12.0/compose.ts
Downloaded
https://deno.land/x/hono@v3.12.0/request.ts
Downloaded
https://deno.land/x/hono@v3.12.0/router.ts
Downloaded
https://deno.land/x/hono@v3.12.0/router/reg-exp-router/node.ts
Downloaded
https://deno.land/x/hono@v3.12.0/router/reg-exp-router/trie.ts
Downloaded
https://deno.land/x/hono@v3.12.0/router/trie-router/node.ts
Downloaded
https://deno.land/x/hono@v3.12.0/client/utils.ts
Downloaded
https://deno.land/x/hono@v3.12.0/utils/jwt/jwt.ts
Downloaded
https://deno.land/x/hono@v3.12.0/utils/stream.ts
Downloaded
https://deno.land/x/redis@v0.32.0/connection.ts
Downloaded
https://deno.land/x/redis@v0.32.0/executor.ts
Downloaded
https://deno.land/x/redis@v0.32.0/pipeline.ts
Downloaded
https://deno.land/x/redis@v0.32.0/pubsub.ts
Downloaded
https://deno.land/x/redis@v0.32.0/stream.ts
Downloaded
https://deno.land/std@0.208.0/log/mod.ts
Downloaded
https://deno.land/x/zod@v3.22.4/external.ts
Downloaded
https://deno.land/x/hono@v3.12.0/utils/body.ts
Downloaded
https://deno.land/x/hono@v3.12.0/utils/jwt/types.ts
Downloaded
https://deno.land/x/redis@v0.32.0/protocol/deno_streams/mod.ts
Downloaded
https://deno.land/x/redis@v0.32.0/backoff.ts
Downloaded
https://deno.land/x/redis@v0.32.0/internal/symbols.ts
Downloaded
https://deno.land/x/redis@v0.32.0/vendor/https/deno.land/std/async/deferred.ts
Downloaded
https://deno.land/x/redis@v0.32.0/vendor/https/deno.land/std/async/delay.ts
Downloaded
https://deno.land/x/redis@v0.32.0/internal/encoding.ts
Downloaded
https://deno.land/std@0.208.0/log/logger.ts
Downloaded
https://deno.land/std@0.208.0/log/handlers.ts
Downloaded
https://deno.land/std@0.208.0/assert/assert.ts
Downloaded
https://deno.land/std@0.208.0/log/levels.ts
Downloaded
https://deno.land/x/zod@v3.22.4/errors.ts
Downloaded
https://deno.land/x/zod@v3.22.4/helpers/parseUtil.ts
Downloaded
https://deno.land/x/zod@v3.22.4/helpers/typeAliases.ts
Downloaded
https://deno.land/x/zod@v3.22.4/helpers/util.ts
Downloaded
https://deno.land/x/zod@v3.22.4/types.ts
Downloaded
https://deno.land/x/zod@v3.22.4/ZodError.ts
Downloaded
https://deno.land/x/redis@v0.32.0/vendor/https/deno.land/std/io/buf_reader.ts
Downloaded
https://deno.land/x/redis@v0.32.0/vendor/https/deno.land/std/io/buf_writer.ts
Downloaded
https://deno.land/x/redis@v0.32.0/protocol/deno_streams/reply.ts
Downloaded
https://deno.land/x/redis@v0.32.0/protocol/deno_streams/command.ts
Downloaded
https://deno.land/std@0.203.0/async/deferred.ts
Downloaded
https://deno.land/std@0.203.0/async/delay.ts
Downloaded
https://deno.land/std@0.208.0/fmt/colors.ts
Downloaded
https://deno.land/std@0.208.0/fs/exists.ts
Downloaded
https://deno.land/std@0.208.0/io/buf_writer.ts
Downloaded
https://deno.land/std@0.208.0/assert/assertion_error.ts
Downloaded
https://deno.land/x/zod@v3.22.4/locales/en.ts
Downloaded
https://deno.land/x/zod@v3.22.4/helpers/enumUtil.ts
Downloaded
https://deno.land/x/zod@v3.22.4/helpers/errorUtil.ts
Downloaded
https://deno.land/x/zod@v3.22.4/helpers/partialUtil.ts
Downloaded
https://deno.land/std@0.203.0/io/buf_reader.ts
Downloaded
https://deno.land/std@0.203.0/io/buf_writer.ts
Downloaded
https://deno.land/x/redis@v0.32.0/protocol/shared/reply.ts
Downloaded
https://deno.land/x/redis@v0.32.0/protocol/shared/command.ts
Downloaded
https://deno.land/std@0.208.0/bytes/copy.ts
Downloaded
https://deno.land/std@0.203.0/assert/assert.ts
Downloaded
https://deno.land/std@0.203.0/bytes/copy.ts
Downloaded
https://deno.land/x/redis@v0.32.0/vendor/https/deno.land/std/bytes/concat.ts
Downloaded
https://deno.land/std@0.203.0/assert/assertion_error.ts
Downloaded
https://deno.land/std@0.203.0/bytes/concat.ts
Packaging complete
Error The deployment failed: UNCAUGHT_EXCEPTION

TypeError: Deno.permissions.querySync is not a function
    at getHostName (https://deno.land/x/sentry@7.94.1/index.mjs:11183:35)
    at new DenoClient (https://deno.land/x/sentry@7.94.1/index.mjs:11215:41)
    at initAndBind (https://deno.land/x/sentry@7.94.1/index.mjs:10396:18)
    at Module.init (https://deno.land/x/sentry@7.94.1/index.mjs:12445:3)
    at file:///src/src/main.ts:25:9
    at eventLoopTick (ext:core/01_core.js:182:7)
```

**Comment by chillbrodev** [comment]
@getsentry-bot Bump
